### ISSUE TITLE
Error: Unable to inject

### ISSUE THREAD

**Issue by symeonp** [mxmssh/drltrace#11]
Hello Maksim!
I'm stalking your projects  😅 - on a more serious note I've recently
discovered this project and it's very awesome for bug hunting as well. I discovered
some interesting functions while playing with this tool, however I am not able
to inject Microsoft Edge, is this a limitation from DR itself?

```
drltrace -logdir . -- C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe
ERROR: unable to inject
```
Am on a Windows 10 x64 system.
Also, I have another case where if the app crashes, the crashing function won't be shown at the log.
Are you aware of this? Lastly I'm having some issues re compilation but I should open a new issue for that one.

Thanks so much!

**Comment by mxmssh** [comment]
Hi Symeon,

Nice to see you in this project! Thanks for the interest. I  have never tried to inject into Edge, I gonna try and update you. Are you using 64bit drltrace's build for this task ? You can't inject 32bit dynamorio.dll into 64-bit processes.

Regarding the crashing function, drltrace was primarily designed to research malware (they usually don't crash :)), so, thanks for reporting this problem. I think it is more relevant to DR in general...

**Comment by symeonp** [comment]
Ahh! Yep, my bad I used the x86 version, the x64 worked perfectly! 
Unfortunately though it didn't give me modules such as jscript.dll or mshtml.dll as I would expect - it's
pretty much standard window-ish DLLs! I am using the version you have on the releases because
I can't compile with VS 2017. If you have some spare time please do update the releases, maybe you've pushed some fixes! Again thanks, it's a very interesting project and I can finally play a bit with DynamoRIO/learn how you implemented some stuff! 

Cheers

**Comment by mxmssh** [comment]
Yes, I am planning to update this release.

**Comment by symeonp** [comment]
Brilliant, thanks so much!
Am getting some funny ``` ~~drltrace~~ found unknown type xxx in the config file ```

Here's another question, as far as I can tell drltrace so far has the ability to launch binaries and start tracing the calls. Do you think would it possible to add a functionality where drltrace can inject to an already running process (eg IE/Edge) and start recording the trace from that moment?
E.g. am running some javascript inside Edge and want to start looking at the function calls.

If it's easy I'd love to help you implement that. (I need to find a good motivation to start learning DR!). If not, then you could share some TODOs so I could work on those if you don't mind!

Cheers

**Comment by mxmssh** [comment]
Yes, there are a lot of unknown types for drltrace which are not implemented.
Regarding injection, unfortunately, DynamoRIO doesn't support this thing, there is an open issue in the issue tracker about this and it is not easy :)
This is conversation about injection into Linux process: https://github.com/DynamoRIO/dynamorio/issues/2468

**Comment by mxmssh** [comment]
Regarding TODOs, you can take a look on already opened issues, there are a lot of things need to be implemented :)

**Comment by mxmssh** [comment]
For example #5 or #6 issues.
