### ISSUE TITLE
The problem with the arguments

### ISSUE THREAD

**Issue by pokamolodoy406** [mxmssh/drltrace#14]
Hello ) 

I downloaded drltrace_win_x64.rar 
and  then I launched (by the way, is there any way to remove the rows with: ~~ found unknown type XLATEOBJ in the config file ?): 
![1](https://user-images.githubusercontent.com/37054694/46843265-a7685f80-cdda-11e8-9f1b-96218954191a.png)

Here is the result and the logfile name:
![2](https://user-images.githubusercontent.com/37054694/46843299-d1ba1d00-cdda-11e8-96b5-7f68d692460c.png)

I can't figure out where the arguments to the GetLocalTime function are:
![3](https://user-images.githubusercontent.com/37054694/46843341-f8785380-cdda-11e8-9e22-3c92ba588f8c.png)

This function must take one argument:
![4](https://user-images.githubusercontent.com/37054694/46843421-5ad15400-cddb-11e8-9360-e5c12c10b91d.png)
This is my source code with GetLocalTime():
![5](https://user-images.githubusercontent.com/37054694/46843441-6f155100-cddb-11e8-9b45-22df1e2c8694.png)

Why are the arguments for the GetLocalTime function not printed ?)

**Comment by mxmssh** [comment]
Hi, thanks for the interest to this tool. It happens because SYSTEMTIME structure printing is not supported in drltrace (there are hundreds of them that are needed to be implemented) :)

**Comment by mxmssh** [comment]
You can find a list of supported types here: https://github.com/mxmssh/drltrace/blob/master/drltrace_src/drltrace.cpp#L100
