### ISSUE TITLE
drltrace on Windows 10

### ISSUE THREAD

**Issue by e7p** [mxmssh/drltrace#21]
Hi,

as I updated to Windows 10 for some time, I now figured out that drltrace doesn't actually work on Windows 10. When running the example from the readme (32-bit or 64-bit drltrace doesn't matter), the following console output is generated, whilst no log is output or saved in the given directory.

```
C:\drltrace\bin64>drltrace -logdir . -- calc.exe
INFO: C:\Windows\system32\calc.exe sucessfully started, waiting app for exit

C:\drltrace\bin64>
```

Is anyone else running Windows 10 without any issue, or is this a known bug? How could this be probably fixed, or is there some kind of a limitation under current versions of Windows?

Cheers,
Endres

**Comment by mxmssh** [comment]
Hm, I have tested drltrace on Win 10. It should work fine for the calculator 100%.

**Comment by symeonp** [comment]
Hello both,

Yep, that's right, on Windows 10 1903 and above, the shipped DynamoRIO version (drrun.exe) won't work anymore:

> Please note that these older releases do not support recent Windows versions from Windows 10 1809 onward - from https://github.com/DynamoRIO/dynamorio/wiki/Downloads

you need the cron builds (e.g. [DynamoRIO Releases](https://github.com/DynamoRIO/dynamorio/releases). Try to re-compile again with this version of DynamoRIO, that should work!

Cheers,

**Comment by mxmssh** [comment]
Right, I've been using the latest release on Win10. It is sad that I didn't notice that before :) Updated to the latest version + released binaries compiled with latest DynamoRIO. Thanks for reporting that @symeonp and @Endres.
