### ISSUE TITLE
drltrace unable to track executable

### ISSUE THREAD

**Issue by MrVoustache** [mxmssh/drltrace#31]
When I try to track an executable on Windows 10 (my drltrace version is "drltrace custom build -- May  5 2021, 10:09:57". I used the instructions on the How To Build page, for Windows 10 64 bits, and thus I have the included DynamoRio version I guess), I get this issue:
When I try to track a Windows application (calc.exe, explorer.exe...), the tracking stops before the application shows up :
[drltrace.calc.exe.10636.0000.log](https://github.com/mxmssh/drltrace/files/6479367/drltrace.calc.exe.10636.0000.log)

On the other hand, when I try this with a not native application, the application does not start, and I get this message (and no log file). And the application starts normally through PowerShell. Here I tried with audacity:
`PS C:\Program Files (x86)\Audacity> & "C:\Users\admin\Documents\Savegames\build\bin64\drltrace.exe" -- .\audacity.exe
WARNING: cannot write log file into C:\Program Files (x86)\Audacity, writing log into C:\Users\admin\AppData\Roaming\Dr. LTrace instead
INFO: C:\Program Files (x86)\Audacity\audacity.exe sucessfully started, waiting app for exit`

Here is the executable:
[audacity.zip](https://github.com/mxmssh/drltrace/files/6479396/audacity.zip)
But I got the same issues with python3 and steam for example...
Thank you for your help

**Comment by mxmssh** [comment]
Ah, I see the problem. I didn't run your binary but the problem with Steam is that it is 32-bit application. You need to use 32-bit drltrace for 32-bit applications and 64-bit drltrace for 64-bit applications.

**Comment by MrVoustache** [comment]
Ah yes, indeed, It works better with the 32bits installation! I tried with the two installations and it seems to be working just fine now. Thank you very much!
