### ISSUE TITLE
Build Error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32

### ISSUE THREAD

**Issue by simuset** [mxmssh/drltrace#8]
I am trying to build drltrace on a VM istance of Windows 7 x86 but I get the following error after entering the command cmake --build . in the build folder:

![immagine](https://user-images.githubusercontent.com/35301938/35688841-6699fbb4-0772-11e8-8f20-63aabce2f918.png)

I am not too familiar with Windows, is there something I am missing ?

**Comment by simuset** [comment]
And if I try to build from Visual Studio I get the following:

![immagine](https://user-images.githubusercontent.com/35301938/35701070-26530a46-0795-11e8-940e-bddeb9fb687e.png)

**Comment by mxmssh** [comment]
Hi, thank you for your interest! I saw this issue before. Could you provide details of your environment: Visual Studio & cmake versions.

BTW: Despite this error, If you navigate in the binary folder, you can find compiled drltrace which is possible to use. This issue is related to drsyscall.

**Comment by simuset** [comment]
First of all thank you for writing such a wonderful tool. I needed a way to trace the API calls of a collection of malicious samples in an automated way and I could only find heavy GUI tools. drltrace, instead, seems to be a perfect fit for my needs.

My environment is:
- Visual Studio 2013 (v12) Community Edition
- cmake version 3.10.2

**Comment by mxmssh** [comment]
Well, looks like a bug. I will try to reproduce this problem and fix it. Could you try cmake version < 3 ?

**Comment by simuset** [comment]
Just to let you know, you were right, despite the error it is still possible to use drltrace and it works flawlessly.
I will try with cmake version < 3 as soon as possible and let you know if the issue is solved.

**Comment by simuset** [comment]
I tried with cmake version 2.8.12.2 and the error is still there.

**Comment by mxmssh** [comment]
Ok, this is a bug. Will fix it. Thank you.
